APPS C:\Users\LENOVO\Desktop\Git Demo\JavaScript-Project> git push origin main To https://github.com/omdevjadeja2006/JavaScript-Project  ! [rejected]        main -> main (fetch first) error: failed to push some refs to 'https://github.com/omdevjadeja2006/JavaScript-Project' hint: Updates were rejected because the remote contains work that you do not hint: have locally. This is usually caused by another repository pushing to hint: the same ref. If you want to integrate the remote changes, use hint: 'git pull' before pushing again. hint: See the 'Note about fast-forwards' in 'git push --help' for details. PS C:\Users\LENOVO\Desktop\Git Demo\JavaScript-Project> git pull origin main --rebase remote: Enumerating objects: 3, done. remote: Counting objects: 100% (3/3), done. remote: Compressing objects: 100% (1/1), done. remote: Total 2 (delta 0), reused 0 (delta 0), pack-reused 0 (from 0) Unpacking objects: 100% (2/2), 887 bytes | 177.00 KiB/s, done. From https://github.com/omdevjadeja2006/JavaScript-Project  * branch            main       -> FETCH_HEAD    9b2158e..f6679b9  main       -> origin/main CONFLICT (modify/delete): JavaScriptproject/Login.html deleted in HEAD and modified in 2a51429 (Added JavaScript project files from htdocs).  Version 2a51429 (Added JavaScript project files from htdocs) of JavaScriptproject/Login.html left in tree. CONFLICT (modify/delete): JavaScriptproject/add_task.php deleted in HEAD and modified in 2a51429 (Added JavaScript project files from htdocs).  Version 2a51429 (Added JavaScript project files from htdocs) of JavaScriptproject/add_task.php left in tree. CONFLICT (modify/delete): JavaScriptproject/dashboard.php deleted in HEAD and modified in 2a51429 (Added JavaScript project files from htdocs).  Version 2a51429 (Added JavaScript project files from htdocs) of JavaScriptproject/dashboard.php left in tree. CONFLICT (modify/delete): JavaScriptproject/edit_task.php deleted in HEAD and modified in 2a51429 (Added JavaScript project files from htdocs).  Version 2a51429 (Added JavaScript project files from htdocs) of JavaScriptproject/edit_task.php left in tree. CONFLICT (modify/delete): JavaScriptproject/login_process.php deleted in HEAD and modified in 2a51429 (Added JavaScript project files from htdocs).  Version 2a51429 (Added JavaScript project files from htdocs) of JavaScriptproject/login_process.php left in tree. CONFLICT (modify/delete): JavaScriptproject/logout.php deleted in HEAD and modified in 2a51429 (Added JavaScript project files from htdocs).  Version 2a51429 (Added JavaScript project files from htdocs) of JavaScriptproject/logout.php left in tree. CONFLICT (modify/delete): JavaScriptproject/signin.html deleted in HEAD and modified in 2a51429 (Added JavaScript project files from htdocs).  V Added JavaScript project files from htdocs
.git/COMMIT_EDITMSG [unix] (19:18 30/03/2026)                                                                                            1,1 Top
"~/Desktop/Git Demo/JavaScript-Project/.git/COMMIT_EDITMSG" [unix] 39L, 1482BS C:\Users\LENOVO\Desktop\Git Demo\JavaScript-Project> git push origin main
To https://github.com/omdevjadeja2006/JavaScript-Project
 ! [rejected]        main -> main (fetch first)
error: failed to push some refs to 'https://github.com/omdevjadeja2006/JavaScript-Project'
hint: Updates were rejected because the remote contains work that you do not
hint: have locally. This is usually caused by another repository pushing to
hint: the same ref. If you want to integrate the remote changes, use
hint: 'git pull' before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
PS C:\Users\LENOVO\Desktop\Git Demo\JavaScript-Project> git pull origin main --rebase
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (1/1), done.
remote: Total 2 (delta 0), reused 0 (delta 0), pack-reused 0 (from 0)
Unpacking objects: 100% (2/2), 887 bytes | 177.00 KiB/s, done.
From https://github.com/omdevjadeja2006/JavaScript-Project
 * branch            main       -> FETCH_HEAD
   9b2158e..f6679b9  main       -> origin/main
CONFLICT (modify/delete): JavaScriptproject/Login.html deleted in HEAD and modified in 2a51429 (Added JavaScript project files from htdocs).  Version 2a51429 (Added JavaScript project files from htdocs) of JavaScriptproject/Login.html left in tree.
CONFLICT (modify/delete): JavaScriptproject/add_task.php deleted in HEAD and modified in 2a51429 (Added JavaScript project files from htdocs).  Version 2a51429 (Added JavaScript project files from htdocs) of JavaScriptproject/add_task.php left in tree.
CONFLICT (modify/delete): JavaScriptproject/dashboard.php deleted in HEAD and modified in 2a51429 (Added JavaScript project files from htdocs).  Version 2a51429 (Added JavaScript project files from htdocs) of JavaScriptproject/dashboard.php left in tree.
CONFLICT (modify/delete): JavaScriptproject/edit_task.php deleted in HEAD and modified in 2a51429 (Added JavaScript project files from htdocs).  Version 2a51429 (Added JavaScript project files from htdocs) of JavaScriptproject/edit_task.php left in tree.
CONFLICT (modify/delete): JavaScriptproject/login_process.php deleted in HEAD and modified in 2a51429 (Added JavaScript project files from htdocs).  Version 2a51429 (Added JavaScript project files from htdocs) of JavaScriptproject/login_process.php left in tree.
CONFLICT (modify/delete): JavaScriptproject/logout.php deleted in HEAD and modified in 2a51429 (Added JavaScript project files from htdocs).  Version 2a51429 (Added JavaScript project files from htdocs) of JavaScriptproject/logout.php left in tree.
CONFLICT (modify/delete): JavaScriptproject/signin.html deleted in HEAD and modified in 2a51429 (Added JavaScript project files from htdocs).  V
Added JavaScript project files from htdocs

.git/COMMIT_EDITMSG [unix] (19:18 30/03/2026)                                                                                            1,1 Top
"~/Desktop/Git Demo/JavaScript-Project/.git/COMMIT_EDITMSG" [unix] 39L, 1482Bdded JavaScript project files from htdocs